import type { Dictionary } from "./fr";

const en: Dictionary = {
  locale: "en-CA",
  meta: {
    title: "Industrial Condos for Sale in Montréal's East End | 12650–12702 Boul. Industriel",
    description:
      "Industrial units from {min} to {max} sq. ft. for sale at 12650–12702 Boulevard Industriel, Pointe-aux-Trembles, in Montréal's east end. 10' × 12' garage door, washroom and on-site parking. {a40} minutes from Highway 40.",
  },
  nav: {
    skip: "Skip to content",
    menu: "Main menu",
    units: "Units",
    included: "Included",
    building: "Building",
    location: "Location",
    photos: "Photos",
    cta: "Get pricing",
    langLabel: "Language",
    langNames: { fr: "Version française", en: "English version" },
    home: "Boul-Industriel-Montreal, back to top",
  },
  hero: {
    eyebrow: "12650–12702 Boul. Industriel · Pointe-aux-Trembles",
    title: "Industrial condos for sale in Montréal's east end.",
    lead: "Spaces from {min} to {max} sq. ft., each with its own 10' × 12' garage door and washroom, plus on-site parking. {a40} minutes from Highway 40.",
    ctaPrimary: "See the units",
    ctaSecondary: "Get pricing",
    photoAlt: "Aerial view of the building at 12650–12702 Boulevard Industriel, outlined in white at the centre of the photo.",
    pinTitle: "12650–12702 Boul. Industriel",
    pinDetail: "Pointe-aux-Trembles · East end",
    platesLabel: "Units for sale",
    platesHint: "Scroll",
    plateAria: "Unit {unit}, {sqft}. Show on the plan",
    areaOnRequest: "On request",
    price: "Price on request",
    priceCta: "Request pricing",
  },
  plan: {
    eyebrow: "Building plan",
    title: "Choose your unit.",
    intro:
      "The building has 24 units, back to back on a single level. Units in green are for sale; the others have already sold. Hover over or tap a unit to find it in the list.",
    aria: "Schematic building plan: 24 units in two rows. Units for sale: {list}. Sold units: {sold}.",
    street: "Boulevard Industriel",
    length: "≈ 490 ft",
    depth: "70 ft",
    service: "Electrical room",
    legendSale: "For sale",
    legendSold: "Sold",
    sold: "SOLD",
    scrollHint: "Swipe to see the whole plan",
    note: "Schematic plan, approximately to scale. Availability as of {date}.",
    listTitle: "Units for sale",
    listHint: "Scroll the list to see every unit.",
    headUnit: "Unit",
    headArea: "Area",
    headAccess: "Access",
    areaOnRequest: "On request",
    through: "Through unit: doors on both sides",
    standard: "10' × 12' garage door and dedicated entrance",
    status: "For sale",
    request: "Request price",
    requestAria: "Request the price of unit {unit}",
  },
  included: {
    eyebrow: "What's included",
    title: "Everything your business needs.",
    lead: "An existing building, ready to move in: no waiting on construction.",
    drawingTitle: "Typical unit, plan view",
    drawingNote: "For illustration only. Layouts vary from unit to unit.",
    drawing: {
      garage: "Garage door",
      door: "Door",
      window: "Window",
      panel: "Electrical",
      washroom: "Washroom",
      heater: "Water heater",
      open: "Open floor",
      width: "10 ft",
    },
    items: [
      { title: "10' × 12' garage door" },
      { title: "Dedicated entrance with its own civic address" },
      { title: "Separate electrical entrance: each unit separately metered" },
      { title: "Washroom and water heater" },
      {
        title: "Combinable units",
        body: "Combine multiple units to create a larger, flexible space that fits your business needs.",
      },
      {
        title: "In the Pointe-aux-Trembles industrial park",
        body: "An established business hub serving local companies across Montréal's east end.",
      },
      {
        title: "Experienced management",
        body: "The property is managed by a strong, experienced management team.",
      },
    ],
  },
  why: {
    eyebrow: "Own instead of rent",
    title: "Own your space.",
    lead: "Whether you're moving your business in or looking for an investment, a unit in your name works for you.",
    ownerTitle: "For your business",
    items: [
      {
        title: "Your payments build equity",
        body: "Every mortgage payment adds value to your company's balance sheet instead of a landlord's.",
      },
      {
        title: "Your costs stay predictable",
        body: "No more increases at lease renewal. Plan over 10 or 20 years, not 3.",
      },
      {
        title: "You fit it out your way",
        body: "Workbenches, racking, a mezzanine, an office: you decide without asking permission.",
      },
      {
        title: "A scarce asset on the island",
        body: "Small industrial spaces for sale are hard to find in Montréal. A well-located unit is easy to resell or lease.",
      },
    ],
    investor: {
      eyebrow: "For investors",
      title: "An investment that pays.",
      body: "You don't have to occupy the unit yourself: lease it to a business in the area. Small industrial spaces are in high demand in Montréal's east end.",
      points: ["Monthly rental income", "Strong tenant demand", "A tangible asset in your name"],
      cta: "Talk to the team",
    },
  },
  building: {
    eyebrow: "The building",
    title: "24 units on a single level.",
    lead: "A {sqft} sq ft industrial building, built in {year} on a {acres}‑acre lot, with parking all around.",
    photoAlt: "Aerial view of the area, with the building for sale outlined in white.",
    facts: {
      area: "Building area",
      units: "Units",
      unitsValue: "24, on a single level",
      size: "Dimensions",
      year: "Built",
      lot: "Lot",
      lotValue: "{acres} acres",
      parking: "Parking",
      parkingValue: "{ratio} spaces / 1,000 sq ft",
      zoning: "Zoning",
      transit: "Public transit",
      transitValue: "Bus line nearby",
    },
  },
  interior: {
    eyebrow: "Interior",
    title: "Inside the units.",
    alt: "Unit interior, photo {i}",
  },
  gallery: {
    eyebrow: "Photos",
    title: "The building and its surroundings.",
    open: "Enlarge: {alt}",
    close: "Close",
    prev: "Previous photo",
    next: "Next photo",
    counter: "{i} of {n}",
    alts: {
      "aerial-summer": "Aerial view of the area in summer, the building at the centre and the river on the horizon",
      "aerial-southwest": "Aerial view of the building and its parking lots, the highway on the horizon",
      "aerial-top": "Top-down view of the site's two buildings and their parking areas",
      "aerial-outlined": "The building for sale, outlined in white",
      "building-end": "The end of the building and the neighbouring units",
    },
  },
  location: {
    eyebrow: "Location",
    title: "{a40} minutes from Highway 40.",
    lead: "The building sits in Pointe-aux-Trembles' industrial sector in Montréal's east end: quick access to Highways 40 and 25, shops and services nearby, and a workforce that lives in the neighbourhood.",
    timesTitle: "Drive times from the building",
    places: {
      a40: "Highway 40",
      a25: "Highway 25 (Anjou interchange)",
      repentigny: "Repentigny",
      southShore: "South Shore, via the tunnel",
      laval: "Laval",
      downtown: "Downtown Montréal",
      airport: "Montréal-Trudeau Airport",
    },
    min: "min",
    timesNote: "Approximate times, outside rush hour.",
    address: "12650–12702 Boulevard Industriel\nPointe-aux-Trembles, Montréal, Québec H1A 3V2",
    loadMap: "Show the map",
    openMaps: "Open in Google Maps",
    mapTitle: "Map: 12650 Boulevard Industriel, Montréal",
  },
  contact: {
    eyebrow: "Contact",
    title: "Get pricing and visit the units.",
    lead: "Leave your details: we'll send pricing and details for the units you're interested in, then set up a visit.",
    phoneLabel: "By phone",
    team: "Sales team",
    emailLabel: "By email",
    fields: {
      name: "Full name",
      company: "Company (optional)",
      email: "Email",
      phone: "Phone",
      unit: "Unit you're interested in",
      anyUnit: "Not decided yet",
      intent: "You'd like to",
      message: "Message (optional)",
    },
    intents: { prices: "Get pricing", visit: "Visit", question: "Ask a question" },
    submit: "Send my request",
    sending: "Sending…",
    successTitle: "Request sent",
    success: "Thanks {name}. The sales team will be in touch shortly.",
    faster: "In a hurry? Call us:",
    mailtoNote: "Your email app opened with your request. Send the message to complete it.",
    sendError: "Your request didn't go through. Try again or call us at {phone}.",
    errors: {
      name: "Enter your name.",
      email: "Enter a valid email, for example name@company.com.",
      phone: "Enter a 10-digit phone number.",
    },
    consent: "By sending this form, you agree to be contacted about these units.",
    call: "Call",
    mailSubject: "Inquiry: units for sale, Boulevard Industriel",
  },
  footer: {
    disclaimer:
      "Areas, plans and availability are provided for information only and may change without notice. This site does not constitute an offer to sell.",
    rights: "All rights reserved.",
    credit: "Site by Davnoot",
  },
  mobileBar: { call: "Call", cta: "Get pricing" },
  units: { sqft: "sq ft", ft: "ft" },
};

export default en;
