import type { Dictionary } from "./fr";

const en: Dictionary = {
  locale: "en-CA",
  meta: {
    title: "Industrial Condos for Sale in Pointe-aux-Trembles | Boul-Industriel-Montreal",
    description:
      "{n} industrial units from {min} to {max} sq ft for sale at 12650–12702 Boulevard Industriel, Montréal. Every unit has a 10' × 12' garage door, its own electrical entrance and a washroom. {a40} minutes from Highway 40.",
  },
  nav: {
    skip: "Skip to content",
    menu: "Main menu",
    units: "Units",
    included: "Included",
    building: "Building",
    location: "Location",
    photos: "Photos",
    cta: "Get pricing",
    otherLang: "FR",
    otherLangLabel: "Version française",
    home: "Boul-Industriel-Montreal, back to top",
  },
  hero: {
    eyebrow: "Industrial condos for sale · Pointe-aux-Trembles, Montréal",
    count: { one: "unit for sale", other: "units for sale" },
    rest: "on Boulevard Industriel.",
    lead: "Spaces from {min} to {max} sq ft, each with its own 10' × 12' garage door, electrical entrance and washroom. {a40} minutes from Highway 40.",
    ctaPrimary: "See the units",
    ctaSecondary: "Get pricing",
    photoAlt: "Aerial view of the building at 12650–12702 Boulevard Industriel, outlined in white at the centre of the photo.",
    pinTitle: "12650–12702 Boul. Industriel",
    pinDetail: "24 units · {n} for sale",
    platesLabel: "Units for sale",
    plateAria: "Unit {unit}, {sqft} sq ft. Show on the plan",
    price: "Price on request",
    priceCta: "Request pricing",
  },
  plan: {
    eyebrow: "Building plan",
    title: "Choose your unit.",
    intro:
      "The building has 24 units, back to back on a single level. Highlighted units are for sale: hover over or tap one to find it in the list.",
    aria: "Schematic building plan: 24 units in two rows. Units for sale: {list}.",
    street: "Boulevard Industriel",
    length: "≈ 490 ft",
    depth: "70 ft",
    service: "Electrical room",
    legendSale: "For sale",
    legendOther: "Not available",
    scrollHint: "Swipe to see the whole plan",
    note: "Schematic plan, approximately to scale. Availability as of {date}.",
    listTitle: "Units for sale",
    headUnit: "Unit",
    headArea: "Area",
    headAccess: "Access",
    through: "Through unit: doors on both sides",
    standard: "10' × 12' garage door and walk-in door",
    status: "For sale",
    request: "Request price",
    requestAria: "Request the price of unit {unit}",
  },
  included: {
    eyebrow: "In every unit",
    title: "A complete shop, not an empty shell.",
    lead: "The building already stands: no waiting on construction. Every unit has its own entrance, services and washroom.",
    drawingTitle: "Typical unit, plan view",
    drawingNote: "For illustration only. Layouts vary from unit to unit.",
    drawing: {
      garage: "Garage door",
      door: "Door",
      window: "Window",
      panel: "Electrical",
      washroom: "Washroom",
      heater: "Water heater",
      open: "Open floor",
      width: "10 ft",
    },
    items: [
      {
        title: "10' × 12' garage door",
        body: "Big enough to drive a cube van straight into the shop.",
      },
      {
        title: "Separate walk-in door",
        body: "Clients and staff come in without opening the garage door.",
      },
      {
        title: "Separate electrical entrance",
        body: "110 V, 220 V and 550 V, for tools as well as lighting.",
      },
      {
        title: "Washroom and water heater",
        body: "A private washroom and a {gal}‑gallon water heater in every unit.",
      },
      {
        title: "Open floor, natural light",
        body: "A clear floor and windows along the front.",
      },
    ],
  },
  why: {
    eyebrow: "Buy instead of lease",
    title: "Stop paying someone else's rent.",
    items: [
      {
        title: "Your payments build equity",
        body: "Every mortgage payment adds value to your company's balance sheet instead of a landlord's.",
      },
      {
        title: "Your costs stay predictable",
        body: "No more increases at lease renewal. Plan over 10 or 20 years, not 3.",
      },
      {
        title: "You fit it out your way",
        body: "Workbenches, racking, a mezzanine, an office: you decide without asking permission.",
      },
      {
        title: "A scarce asset on the island",
        body: "Small industrial spaces for sale are hard to find in Montréal. A well-located unit is easy to resell or lease.",
      },
    ],
  },
  building: {
    eyebrow: "The building",
    title: "24 units on a single level.",
    lead: "A {sqft} sq ft industrial building, built in {year} on a {acres}‑acre lot, with parking all around.",
    photoAlt: "Aerial view of the area, with the building for sale outlined in white.",
    facts: {
      area: "Building area",
      units: "Units",
      unitsValue: "24, on a single level",
      size: "Dimensions",
      year: "Built",
      lot: "Lot",
      lotValue: "{acres} acres",
      parking: "Parking",
      parkingValue: "{ratio} spaces / 1,000 sq ft",
      zoning: "Zoning",
      transit: "Public transit",
      transitValue: "Bus line nearby",
    },
  },
  gallery: {
    eyebrow: "Photos",
    title: "The building and its surroundings.",
    open: "Enlarge: {alt}",
    close: "Close",
    prev: "Previous photo",
    next: "Next photo",
    counter: "{i} of {n}",
    alts: {
      "aerial-summer": "Aerial view of the area in summer, the building at the centre and the river on the horizon",
      "aerial-southwest": "Aerial view of the building and its parking lots, the highway on the horizon",
      "aerial-top": "Top-down view of the site's two buildings and their parking areas",
      "aerial-outlined": "The building for sale, outlined in white",
      "building-end": "The end of the building and the neighbouring units",
    },
  },
  location: {
    eyebrow: "Location",
    title: "{a40} minutes from Highway 40.",
    lead: "The building sits in Pointe-aux-Trembles' industrial sector in Montréal's east end: quick access to Highways 40 and 25, shops and services nearby, and a workforce that lives in the neighbourhood.",
    timesTitle: "Drive times from the building",
    places: {
      a40: "Highway 40",
      a25: "Highway 25 (Anjou interchange)",
      repentigny: "Repentigny",
      southShore: "South Shore, via the tunnel",
      laval: "Laval",
      downtown: "Downtown Montréal",
      airport: "Montréal-Trudeau Airport",
    },
    min: "min",
    timesNote: "Approximate times, outside rush hour.",
    address: "12650–12702 Boulevard Industriel\nPointe-aux-Trembles, Montréal, Québec H1A 3V2",
    loadMap: "Show the map",
    openMaps: "Open in Google Maps",
    mapTitle: "Map: 12650 Boulevard Industriel, Montréal",
  },
  contact: {
    eyebrow: "Contact",
    title: "Get pricing and visit the units.",
    lead: "Leave your details: we'll send pricing and details for the units you're interested in, then set up a visit.",
    phoneLabel: "By phone",
    team: "Sales team",
    emailLabel: "By email",
    fields: {
      name: "Full name",
      company: "Company (optional)",
      email: "Email",
      phone: "Phone",
      unit: "Unit you're interested in",
      anyUnit: "Not decided yet",
      intent: "You'd like to",
      message: "Message (optional)",
    },
    intents: { prices: "Get pricing", visit: "Visit", question: "Ask a question" },
    submit: "Send my request",
    sending: "Sending…",
    successTitle: "Request sent",
    success: "Thanks {name}. The sales team will be in touch shortly.",
    faster: "In a hurry? Call us:",
    mailtoNote: "Your email app opened with your request. Send the message to complete it.",
    sendError: "Your request didn't go through. Try again or call us at {phone}.",
    errors: {
      name: "Enter your name.",
      email: "Enter a valid email, for example name@company.com.",
      phone: "Enter a 10-digit phone number.",
    },
    consent: "By sending this form, you agree to be contacted about these units.",
    call: "Call",
    mailSubject: "Inquiry: units for sale, Boulevard Industriel",
  },
  footer: {
    disclaimer:
      "Areas, plans and availability are provided for information only and may change without notice. This site does not constitute an offer to sell.",
    rights: "All rights reserved.",
    credit: "Site by Davnoot",
  },
  mobileBar: { call: "Call", cta: "Get pricing" },
  units: { sqft: "sq ft", ft: "ft" },
};

export default en;
