const fr = {
  locale: "fr-CA",
  meta: {
    title: "Condos industriels à vendre à Pointe-aux-Trembles | Boul-Industriel-Montreal",
    description:
      "{n} unités industrielles de {min} à {max} pi² à vendre au 12650–12702, boulevard Industriel, à Montréal. Porte de garage 10' × 12', entrée électrique indépendante et salle de bain dans chaque unité. À {a40} minutes de l'autoroute 40.",
  },
  nav: {
    skip: "Aller au contenu",
    menu: "Menu principal",
    units: "Unités",
    included: "Inclus",
    building: "Bâtiment",
    location: "Emplacement",
    photos: "Photos",
    cta: "Recevoir les prix",
    otherLang: "EN",
    otherLangLabel: "English version",
    home: "Boul-Industriel-Montreal, retour en haut",
  },
  hero: {
    eyebrow: "Condos industriels à vendre · Pointe-aux-Trembles, Montréal",
    count: { one: "unité à vendre", other: "unités à vendre" },
    rest: "sur le boulevard Industriel.",
    lead: "Des locaux de {min} à {max} pi², chacun avec sa porte de garage 10' × 12', sa propre entrée électrique et sa salle de bain. À {a40} minutes de l'autoroute 40.",
    ctaPrimary: "Voir les unités",
    ctaSecondary: "Recevoir les prix",
    photoAlt:
      "Vue aérienne du bâtiment au 12650–12702, boulevard Industriel, encadré en blanc au centre de la photo.",
    pinTitle: "12650–12702, boul. Industriel",
    pinDetail: "24 unités · {n} à vendre",
    platesLabel: "Unités à vendre",
    plateAria: "Unité {unit}, {sqft} pi². Voir sur le plan",
    price: "Prix sur demande",
    priceCta: "Demander les prix",
  },
  plan: {
    eyebrow: "Plan du bâtiment",
    title: "Choisissez votre unité.",
    intro:
      "Le bâtiment compte 24 unités, dos à dos sur un seul niveau. Les unités en surbrillance sont à vendre : survolez-en ou touchez-en une pour la retrouver dans la liste.",
    aria: "Plan schématique du bâtiment : 24 unités sur deux rangées. Unités à vendre : {list}.",
    street: "Boulevard Industriel",
    length: "≈ 490 pi",
    depth: "70 pi",
    service: "Salle électrique",
    legendSale: "À vendre",
    legendOther: "Non disponible",
    scrollHint: "Glissez pour voir tout le plan",
    note: "Plan schématique, à l'échelle approximative. Disponibilités au {date}.",
    listTitle: "Unités à vendre",
    headUnit: "Unité",
    headArea: "Superficie",
    headAccess: "Accès",
    through: "Unité traversante : portes des deux côtés",
    standard: "Porte de garage 10' × 12' et porte piétonne",
    status: "À vendre",
    request: "Demander le prix",
    requestAria: "Demander le prix de l'unité {unit}",
  },
  included: {
    eyebrow: "Dans chaque unité",
    title: "Un atelier complet, pas une coquille vide.",
    lead: "Le bâtiment existe déjà : pas d'attente de construction. Chaque unité a son entrée, ses services et sa salle de bain.",
    drawingTitle: "Unité type, vue en plan",
    drawingNote: "Schéma indicatif. L'aménagement varie d'une unité à l'autre.",
    drawing: {
      garage: "Porte de garage",
      door: "Porte",
      window: "Fenêtre",
      panel: "Électricité",
      washroom: "S. de bain",
      heater: "Chauffe-eau",
      open: "Aire ouverte",
      width: "10 pi",
    },
    items: [
      {
        title: "Porte de garage 10' × 12'",
        body: "Assez grande pour faire entrer un camion cube directement dans l'atelier.",
      },
      {
        title: "Porte piétonne indépendante",
        body: "Clients et employés entrent sans ouvrir la porte de garage.",
      },
      {
        title: "Entrée électrique indépendante",
        body: "110 V, 220 V et 550 V, pour l'outillage comme pour l'éclairage.",
      },
      {
        title: "Salle de bain et chauffe‑eau",
        body: "Une salle de bain privée et un chauffe-eau de {gal} gallons dans chaque unité.",
      },
      {
        title: "Aire ouverte, lumière naturelle",
        body: "Un plancher dégagé et des fenêtres en façade.",
      },
    ],
  },
  why: {
    eyebrow: "Acheter plutôt que louer",
    title: "Arrêtez de payer le loyer de quelqu'un d'autre.",
    items: [
      {
        title: "Vos paiements bâtissent votre avoir",
        body: "Chaque versement hypothécaire ajoute de la valeur au bilan de votre entreprise au lieu d'enrichir un propriétaire.",
      },
      {
        title: "Vos coûts restent prévisibles",
        body: "Plus de hausse imposée au renouvellement du bail. Vous planifiez sur 10 ou 20 ans, pas sur 3.",
      },
      {
        title: "Vous aménagez à votre façon",
        body: "Établis, rayonnages, mezzanine, bureau : vous décidez sans demander la permission.",
      },
      {
        title: "Un actif rare sur l'île",
        body: "Les petits locaux industriels à vendre se font rares à Montréal. Une unité bien située se revend ou se loue facilement.",
      },
    ],
  },
  building: {
    eyebrow: "Le bâtiment",
    title: "24 unités sur un seul niveau.",
    lead: "Un bâtiment industriel de {sqft} pi² construit en {year} sur un terrain de {acres} acres, avec du stationnement tout autour.",
    photoAlt: "Vue aérienne du secteur, le bâtiment à vendre encadré en blanc.",
    facts: {
      area: "Superficie du bâtiment",
      units: "Unités",
      unitsValue: "24, sur un seul niveau",
      size: "Dimensions",
      year: "Construction",
      lot: "Terrain",
      lotValue: "{acres} acres",
      parking: "Stationnement",
      parkingValue: "{ratio} cases / 1 000 pi²",
      zoning: "Zonage",
      transit: "Transport en commun",
      transitValue: "Ligne d'autobus à proximité",
    },
  },
  gallery: {
    eyebrow: "Photos",
    title: "Le bâtiment et son secteur.",
    open: "Agrandir : {alt}",
    close: "Fermer",
    prev: "Photo précédente",
    next: "Photo suivante",
    counter: "{i} sur {n}",
    alts: {
      "aerial-summer": "Vue aérienne du secteur en été, le bâtiment au centre et le fleuve à l'horizon",
      "aerial-southwest": "Vue aérienne du bâtiment et de ses stationnements, l'autoroute à l'horizon",
      "aerial-top": "Vue du dessus des deux bâtiments du site et de leurs aires de stationnement",
      "aerial-outlined": "Le bâtiment à vendre, encadré en blanc",
      "building-end": "L'extrémité du bâtiment et les unités voisines",
    } as Record<string, string>,
  },
  location: {
    eyebrow: "Emplacement",
    title: "À {a40} minutes de l'autoroute 40.",
    lead: "Le bâtiment est dans le secteur industriel de Pointe-aux-Trembles, dans l'est de Montréal : accès rapide aux autoroutes 40 et 25, commerces et services à proximité, et une main-d'œuvre qui habite le quartier.",
    timesTitle: "Temps de route depuis le bâtiment",
    places: {
      a40: "Autoroute 40",
      a25: "Autoroute 25 (échangeur Anjou)",
      repentigny: "Repentigny",
      southShore: "Rive-Sud, par le tunnel",
      laval: "Laval",
      downtown: "Centre-ville de Montréal",
      airport: "Aéroport Montréal-Trudeau",
    } as Record<string, string>,
    min: "min",
    timesNote: "Temps approximatifs, hors heures de pointe.",
    address: "12650–12702, boulevard Industriel\nPointe-aux-Trembles, Montréal (Québec) H1A 3V2",
    loadMap: "Afficher la carte",
    openMaps: "Ouvrir dans Google Maps",
    mapTitle: "Carte : 12650, boulevard Industriel, Montréal",
  },
  contact: {
    eyebrow: "Contact",
    title: "Recevez les prix et visitez les unités.",
    lead: "Laissez vos coordonnées : on vous envoie les prix et les détails des unités qui vous intéressent, puis on planifie une visite.",
    phoneLabel: "Par téléphone",
    team: "Équipe des ventes",
    emailLabel: "Par courriel",
    fields: {
      name: "Nom complet",
      company: "Entreprise (facultatif)",
      email: "Courriel",
      phone: "Téléphone",
      unit: "Unité qui vous intéresse",
      anyUnit: "Pas encore décidé",
      intent: "Vous souhaitez",
      message: "Message (facultatif)",
    },
    intents: { prices: "Recevoir les prix", visit: "Visiter", question: "Poser une question" },
    submit: "Envoyer ma demande",
    sending: "Envoi en cours…",
    successTitle: "Demande envoyée",
    success: "Merci {name}. L'équipe des ventes vous contacte sous peu.",
    faster: "Pour aller plus vite, appelez-nous :",
    mailtoNote: "Votre logiciel de courriel s'est ouvert avec votre demande. Envoyez le message pour la compléter.",
    sendError: "L'envoi n'a pas fonctionné. Réessayez ou appelez-nous au {phone}.",
    errors: {
      name: "Entrez votre nom.",
      email: "Entrez un courriel valide, par exemple nom@entreprise.com.",
      phone: "Entrez un numéro de téléphone à 10 chiffres.",
    },
    consent: "En envoyant ce formulaire, vous acceptez d'être contacté au sujet de ces unités.",
    call: "Appeler",
    mailSubject: "Demande : unités à vendre, boulevard Industriel",
  },
  footer: {
    disclaimer:
      "Superficies, plans et disponibilités sont fournis à titre indicatif et peuvent changer sans préavis. Ce site ne constitue pas une offre de vente.",
    rights: "Tous droits réservés.",
    credit: "Site par Davnoot",
  },
  mobileBar: { call: "Appeler", cta: "Recevoir les prix" },
  units: { sqft: "pi²", ft: "pi" },
};

export default fr;
export type Dictionary = typeof fr;
