const fr = {
  locale: "fr-CA",
  meta: {
    title: "Condos industriels à vendre dans l'est de Montréal | 12650–12702, boul. Industriel",
    description:
      "Unités industrielles de {min} à {max} pi² à vendre au 12650–12702, boulevard Industriel, à Pointe-aux-Trembles, dans l'est de Montréal. Porte de garage 10' × 12', salle de bain et stationnement sur place. À {a40} minutes de l'autoroute 40.",
  },
  nav: {
    skip: "Aller au contenu",
    menu: "Menu principal",
    units: "Unités",
    included: "Inclus",
    building: "Bâtiment",
    location: "Emplacement",
    photos: "Photos",
    cta: "Recevoir les prix",
    langLabel: "Langue",
    langNames: { fr: "Version française", en: "English version" },
    home: "Boul-Industriel-Montreal, retour en haut",
  },
  hero: {
    eyebrow: "12650–12702, boul. Industriel · Pointe-aux-Trembles",
    title: "Condos industriels à vendre dans l'est de Montréal.",
    lead: "Des locaux de {min} à {max} pi², chacun avec sa porte de garage 10' × 12' et sa salle de bain, et du stationnement sur place. À {a40} minutes de l'autoroute 40.",
    ctaPrimary: "Voir les unités",
    ctaSecondary: "Recevoir les prix",
    photoAlt:
      "Vue aérienne du bâtiment au 12650–12702, boulevard Industriel, encadré en blanc au centre de la photo.",
    pinTitle: "12650–12702, boul. Industriel",
    pinDetail: "Pointe-aux-Trembles · Est de Montréal",
    platesLabel: "Unités à vendre",
    platesHint: "Faites défiler",
    plateAria: "Unité {unit}, {sqft}. Voir sur le plan",
    areaOnRequest: "Sur demande",
    price: "Prix sur demande",
    priceCta: "Demander les prix",
  },
  plan: {
    eyebrow: "Plan du bâtiment",
    title: "Choisissez votre unité.",
    intro:
      "Le bâtiment compte 24 unités, dos à dos sur un seul niveau. Les unités en vert sont à vendre, les autres ont déjà trouvé preneur. Survolez ou touchez une unité pour la retrouver dans la liste.",
    aria: "Plan schématique du bâtiment : 24 unités sur deux rangées. Unités à vendre : {list}. Unités vendues : {sold}.",
    street: "Boulevard Industriel",
    length: "≈ 490 pi",
    depth: "70 pi",
    service: "Salle électrique",
    legendSale: "À vendre",
    legendSold: "Vendu",
    sold: "VENDU",
    scrollHint: "Glissez pour voir tout le plan",
    note: "Plan schématique, à l'échelle approximative. Disponibilités au {date}.",
    listTitle: "Unités à vendre",
    listHint: "Faites défiler la liste pour voir toutes les unités.",
    headUnit: "Unité",
    headArea: "Superficie",
    headAccess: "Accès",
    areaOnRequest: "Sur demande",
    through: "Unité traversante : portes des deux côtés",
    standard: "Porte de garage 10' × 12' et entrée indépendante",
    status: "À vendre",
    request: "Demander le prix",
    requestAria: "Demander le prix de l'unité {unit}",
  },
  included: {
    eyebrow: "Ce qui est inclus",
    title: "Tout ce dont votre entreprise a besoin.",
    lead: "Un bâtiment existant, prêt à occuper : pas d'attente de construction.",
    drawingTitle: "Unité type, vue en plan",
    drawingNote: "Schéma indicatif. L'aménagement varie d'une unité à l'autre.",
    drawing: {
      garage: "Porte de garage",
      door: "Porte",
      window: "Fenêtre",
      panel: "Électricité",
      washroom: "S. de bain",
      heater: "Chauffe-eau",
      open: "Aire ouverte",
      width: "10 pi",
    },
    items: [
      { title: "Porte de garage 10' × 12'" },
      { title: "Entrée indépendante avec son propre numéro civique" },
      { title: "Entrée électrique indépendante : chaque unité a son propre compteur" },
      { title: "Salle de bain et chauffe-eau" },
      {
        title: "Unités combinables",
        body: "Réunissez plusieurs unités pour créer un espace plus grand et flexible, adapté aux besoins de votre entreprise.",
      },
      {
        title: "Au cœur du parc industriel de Pointe-aux-Trembles",
        body: "Un secteur d'affaires établi, au service des entreprises locales de l'est de Montréal.",
      },
      {
        title: "Une équipe de gestion d'expérience",
        body: "L'immeuble est géré par une équipe de gestion solide et expérimentée.",
      },
    ] as { title: string; body?: string }[],
  },
  why: {
    eyebrow: "Propriétaire plutôt que locataire",
    title: "Soyez propriétaire de vos locaux.",
    lead: "Que ce soit pour y installer votre entreprise ou pour investir, une unité à votre nom travaille pour vous.",
    ownerTitle: "Pour votre entreprise",
    items: [
      {
        title: "Vos paiements bâtissent votre avoir",
        body: "Chaque versement hypothécaire ajoute de la valeur au bilan de votre entreprise au lieu d'enrichir un propriétaire.",
      },
      {
        title: "Vos coûts restent prévisibles",
        body: "Plus de hausse imposée au renouvellement du bail. Vous planifiez sur 10 ou 20 ans, pas sur 3.",
      },
      {
        title: "Vous aménagez à votre façon",
        body: "Établis, rayonnages, mezzanine, bureau : vous décidez sans demander la permission.",
      },
      {
        title: "Un actif rare sur l'île",
        body: "Les petits locaux industriels à vendre se font rares à Montréal. Une unité bien située se revend ou se loue facilement.",
      },
    ],
    investor: {
      eyebrow: "Pour les investisseurs",
      title: "Un placement qui rapporte.",
      body: "Pas besoin d'occuper l'unité vous-même : louez-la à une entreprise du secteur. Les petits locaux industriels sont très recherchés dans l'est de Montréal.",
      points: ["Des revenus de location chaque mois", "Une forte demande de locataires", "Un actif tangible, à votre nom"],
      cta: "Parler à l'équipe",
    },
  },
  building: {
    eyebrow: "Le bâtiment",
    title: "24 unités sur un seul niveau.",
    lead: "Un bâtiment industriel de {sqft} pi² construit en {year} sur un terrain de {acres} acres, avec du stationnement tout autour.",
    photoAlt: "Vue aérienne du secteur, le bâtiment à vendre encadré en blanc.",
    facts: {
      area: "Superficie du bâtiment",
      units: "Unités",
      unitsValue: "24, sur un seul niveau",
      size: "Dimensions",
      year: "Construction",
      lot: "Terrain",
      lotValue: "{acres} acres",
      parking: "Stationnement",
      parkingValue: "{ratio} cases / 1 000 pi²",
      zoning: "Zonage",
      transit: "Transport en commun",
      transitValue: "Ligne d'autobus à proximité",
    },
  },
  interior: {
    eyebrow: "Intérieur",
    title: "À l'intérieur des unités.",
    alt: "Intérieur d'une unité, photo {i}",
  },
  gallery: {
    eyebrow: "Photos",
    title: "Le bâtiment et son secteur.",
    open: "Agrandir : {alt}",
    close: "Fermer",
    prev: "Photo précédente",
    next: "Photo suivante",
    counter: "{i} sur {n}",
    alts: {
      "aerial-summer": "Vue aérienne du secteur en été, le bâtiment au centre et le fleuve à l'horizon",
      "aerial-southwest": "Vue aérienne du bâtiment et de ses stationnements, l'autoroute à l'horizon",
      "aerial-top": "Vue du dessus des deux bâtiments du site et de leurs aires de stationnement",
      "aerial-outlined": "Le bâtiment à vendre, encadré en blanc",
      "building-end": "L'extrémité du bâtiment et les unités voisines",
    } as Record<string, string>,
  },
  location: {
    eyebrow: "Emplacement",
    title: "À {a40} minutes de l'autoroute 40.",
    lead: "Le bâtiment est dans le secteur industriel de Pointe-aux-Trembles, dans l'est de Montréal : accès rapide aux autoroutes 40 et 25, commerces et services à proximité, et une main-d'œuvre qui habite le quartier.",
    timesTitle: "Temps de route depuis le bâtiment",
    places: {
      a40: "Autoroute 40",
      a25: "Autoroute 25 (échangeur Anjou)",
      repentigny: "Repentigny",
      southShore: "Rive-Sud, par le tunnel",
      laval: "Laval",
      downtown: "Centre-ville de Montréal",
      airport: "Aéroport Montréal-Trudeau",
    } as Record<string, string>,
    min: "min",
    timesNote: "Temps approximatifs, hors heures de pointe.",
    address: "12650–12702, boulevard Industriel\nPointe-aux-Trembles, Montréal (Québec) H1A 3V2",
    loadMap: "Afficher la carte",
    openMaps: "Ouvrir dans Google Maps",
    mapTitle: "Carte : 12650, boulevard Industriel, Montréal",
  },
  contact: {
    eyebrow: "Contact",
    title: "Recevez les prix et visitez les unités.",
    lead: "Laissez vos coordonnées : on vous envoie les prix et les détails des unités qui vous intéressent, puis on planifie une visite.",
    phoneLabel: "Par téléphone",
    team: "Équipe des ventes",
    emailLabel: "Par courriel",
    fields: {
      name: "Nom complet",
      company: "Entreprise (facultatif)",
      email: "Courriel",
      phone: "Téléphone",
      unit: "Unité qui vous intéresse",
      anyUnit: "Pas encore décidé",
      intent: "Vous souhaitez",
      message: "Message (facultatif)",
    },
    intents: { prices: "Recevoir les prix", visit: "Visiter", question: "Poser une question" },
    submit: "Envoyer ma demande",
    sending: "Envoi en cours…",
    successTitle: "Demande envoyée",
    success: "Merci {name}. L'équipe des ventes vous contacte sous peu.",
    faster: "Pour aller plus vite, appelez-nous :",
    mailtoNote: "Votre logiciel de courriel s'est ouvert avec votre demande. Envoyez le message pour la compléter.",
    sendError: "L'envoi n'a pas fonctionné. Réessayez ou appelez-nous au {phone}.",
    errors: {
      name: "Entrez votre nom.",
      email: "Entrez un courriel valide, par exemple nom@entreprise.com.",
      phone: "Entrez un numéro de téléphone à 10 chiffres.",
    },
    consent: "En envoyant ce formulaire, vous acceptez d'être contacté au sujet de ces unités.",
    call: "Appeler",
    mailSubject: "Demande : unités à vendre, boulevard Industriel",
  },
  footer: {
    disclaimer:
      "Superficies, plans et disponibilités sont fournis à titre indicatif et peuvent changer sans préavis. Ce site ne constitue pas une offre de vente.",
    rights: "Tous droits réservés.",
    credit: "Site par Davnoot",
  },
  mobileBar: { call: "Appeler", cta: "Recevoir les prix" },
  units: { sqft: "pi²", ft: "pi" },
};

export default fr;
export type Dictionary = typeof fr;
